using Runeheir.Cameras;
using Runeheir.Characters;
using Runeheir.Controls;
using Runeheir.Movement;
using Runeheir.Online;
using Runeheir.Player;
using Runeheir.Session;
using Runeheir.UI;
using Runeheir.World;
using Runeheir.WorldBuilding;
using UnityEngine;
using UnityEngine.AI;

namespace Runeheir.Field
{
    /// <summary>
    /// Entry point of a map. In the RH_World scene (<see cref="generateMap"/>) it builds the map the character is on from
    /// the Core <see cref="MapCatalog"/> (Phase 5: all 14 maps are generated into that one scene), then spawns the character
    /// at the portal they came through, their saved spot or the save point; places the map's portals, NPCs, monsters and
    /// bosses; points the isometric camera at the player, builds the HUD and autosaves.
    /// In a hand-built scene (the PlayMode test field) it uses the scene's own environment and save point instead.
    /// Pressing Play directly creates a temporary character for quick iteration, starting on <see cref="mapId"/>.
    /// </summary>
    public sealed class FieldBootstrap : MonoBehaviour
    {
        [Tooltip("Generated maps: the map a temporary character (Play pressed in this scene) starts on. Hand-built scenes: this scene's map.")]
        [SerializeField] private string mapId = MapCatalog.WhisperwoodPlains;

        [Tooltip("Build the map from the world catalog at load time (the RH_World scene). Off = use this scene's own environment.")]
        [SerializeField] private bool generateMap;

        [SerializeField] private Transform savePoint;
        [SerializeField] private IsometricCameraRig cameraRig;

        [Tooltip("Optional character model with an Animator. Empty = placeholder avatar. RuneheirSettings (Resources) wins when set: " +
                 "this scene is regenerated by every build, so set your model there.")]
        [SerializeField] private GameObject playerVisualPrefab;

        [Tooltip("Hand-built scenes: random-teleport area (Wind Rune Shard), centered on this object.")]
        [SerializeField] private Vector3 mapSize = new Vector3(130f, 20f, 130f);

        [Header("Server rates (XileRO-style high rate)")]
        [SerializeField, Min(0f)] private float baseExpRate = 50f;
        [SerializeField, Min(0f)] private float jobExpRate = 50f;
        [SerializeField, Min(0f)] private float dropRate = 5f;

        [SerializeField, Min(5f)] private float autosaveSeconds = 60f;

        private PlayerCharacter _player;
        private float _nextAutosave;
        private bool _saveOnAttach;
        private HudController _hud;

        /// <summary>The map that is up right now (online, the network layer hands it the character when it arrives).</summary>
        public static FieldBootstrap Active { get; private set; }

        public PlayerCharacter Player => _player;

        /// <summary>The generated map (null in hand-built scenes).</summary>
        public BuiltWorld World { get; private set; }

        public bool GeneratesMap
        {
            get => generateMap;
            set => generateMap = value;
        }

        public string MapId
        {
            get => mapId;
            set => mapId = value;
        }

        private void Awake()
        {
            Active = this;
        }

        private void OnDestroy()
        {
            if (Active == this)
            {
                Active = null;
            }
        }

        private void Start()
        {
            var settings = RuneheirSettings.Instance;
            var online = OnlineSession.Current;
            if (online == null)
            {
                // Online, the realm sets the rates (and its monsters are the only ones that use them).
                ServerRates.Current = settings != null && settings.overrideRates
                    ? new ServerRates { BaseExp = settings.baseExpRate, JobExp = settings.jobExpRate, Drop = settings.dropRate, CardDrop = settings.cardDropRate }
                    : new ServerRates { BaseExp = baseExpRate, JobExp = jobExpRate, Drop = dropRate };
            }

            EventSystemBootstrap.Ensure();
            ResolveCameraRig();

            var session = GameSession.Instance;
            bool fresh = session.ActiveCharacter == null;
            var record = session.ActiveCharacter ?? session.CreateTemporaryCharacter();
            if (fresh && MapCatalog.Get(mapId) != null)
            {
                record.MapId = mapId; // Play pressed in this scene: start where the scene says
            }

            Vector3 save;
            string arrivalPortal = null;
            bool warped = false;
            bool hostedCopy = false;
            var camera = cameraRig != null ? cameraRig.GetComponent<Camera>() : Camera.main;
            if (generateMap)
            {
                warped = WorldTravel.TakeArrival(out arrivalPortal);
                var map = MapCatalog.Get(record.MapId) ?? MapCatalog.Get(MapCatalog.StartingMapId);
                if (online != null)
                {
                    // Online, every map has its own spot in the world. A host shows the realm's own copy of the map;
                    // a client builds the same map at the same spot, so positions agree.
                    World = online.HostedWorld(map.Id);
                    hostedCopy = World != null;
                    if (hostedCopy)
                    {
                        World.ApplyAtmosphere(camera);
                    }
                    else
                    {
                        var origin = WorldGrid.Origin(map.Id);
                        World = WorldBuilder.Build(map, camera, new Vector3(origin.X, 0f, origin.Z), applyAtmosphere: true);
                    }
                }
                else
                {
                    World = WorldBuilder.Build(map, camera);
                }

                save = World.SavePoint;
                FieldContext.Set(map.Id, map.Name, save, World.Bounds, World.Layout, World.Origin);
            }
            else
            {
                save = savePoint != null ? savePoint.position : transform.position;
                var map = MapCatalog.Get(mapId);
                FieldContext.Set(mapId, map != null ? map.Name : mapId, save, new Bounds(transform.position, mapSize));
                BakeHandBuiltNavMesh();
            }

            Vector3 spawn = SpawnPoint(record, save, arrivalPortal);
            if (NavMesh.SamplePosition(spawn, out NavMeshHit hit, 10f, NavMesh.AllAreas))
            {
                spawn = hit.position;
            }

            if (online != null && World != null)
            {
                // The realm runs the monsters; NPCs and portals are ours to place (a host's copy already has them).
                if (!hostedCopy)
                {
                    WorldPopulator.Populate(World, monsters: false);
                }

                WorldUiLayer.Create();
                _saveOnAttach = warped;
                online.EnterMap(World.Map.Id, spawn);
                return; // AttachPlayer runs when the realm's spawn of our character arrives
            }

            var visual = settings != null && settings.playerVisualPrefab != null ? settings.playerVisualPrefab : playerVisualPrefab;
            _player = EntityFactory.CreatePlayer(record, spawn, visual, settings != null ? settings.playerAnimatorController : null);

            // NPCs, portals and boss lairs before the HUD: its minimap marks them.
            if (World != null)
            {
                WorldPopulator.Populate(World);
            }
            else
            {
                NpcActor.SpawnTownNpcs(save);
            }

            _saveOnAttach = warped;
            AttachPlayer(_player);
        }

        /// <summary>
        /// Builds the local character's object (online, the network layer calls this when the realm spawns it, with its
        /// network components added before the object wakes up).
        /// </summary>
        public PlayerCharacter CreatePlayerObject(Characters.CharacterRecord record, Vector3 position, System.Action<GameObject> beforeActivate)
        {
            var settings = RuneheirSettings.Instance;
            var visual = settings != null && settings.playerVisualPrefab != null ? settings.playerVisualPrefab : playerVisualPrefab;
            return EntityFactory.CreatePlayer(record, position, visual, settings != null ? settings.playerAnimatorController : null, beforeActivate);
        }

        /// <summary>The character is in the world: camera, HUD, greeting and saves.</summary>
        public void AttachPlayer(PlayerCharacter player)
        {
            if (player == null || (_player == player && _hud != null))
            {
                return;
            }

            _player = player;
            if (cameraRig != null)
            {
                cameraRig.SetTarget(_player.transform, snap: true);
            }

            WorldUiLayer.Create();

            // Online, every map the realm puts you on brings a new character object: the old HUD (and its chat box, still
            // bound to the old object) must go, or typed commands reach a character that no longer exists.
            if (_hud != null)
            {
                Destroy(_hud.gameObject);
            }

            _hud = HudController.Create(_player, this);
            if (World != null)
            {
                _hud.ShowMapBanner(World.Map);
            }

            WorldTravel.FinishArrival();
            Greet(_player.Record, GameSession.Instance);
            _player.ReturnCartGoods(); // a stall that closed with the game, a trade that didn't fit
            if (_saveOnAttach)
            {
                _saveOnAttach = false;
                _player.SaveNow(); // the warp's save, now that the character stands on the new map
            }

            _nextAutosave = Time.time + autosaveSeconds;
        }

        private void ResolveCameraRig()
        {
            if (cameraRig == null && Camera.main != null)
            {
                // Explicit null checks: Unity's fake-null objects make "??" unreliable here.
                cameraRig = Camera.main.GetComponent<IsometricCameraRig>();
                if (cameraRig == null)
                {
                    cameraRig = Camera.main.gameObject.AddComponent<IsometricCameraRig>();
                }
            }
        }

        private static void BakeHandBuiltNavMesh()
        {
            if (!RuntimeNavMeshBaker.HasAnyNavMesh)
            {
                foreach (var baker in FindObjectsByType<RuntimeNavMeshBaker>(FindObjectsSortMode.None))
                {
                    baker.EnsureBaked();
                }
            }

            if (!RuntimeNavMeshBaker.HasAnyNavMesh)
            {
                Debug.LogError("[Runeheir] No NavMesh in this scene. Add a RuntimeNavMeshBaker to the environment root, " +
                               "or bake a NavMeshSurface (AI Navigation package).");
            }
        }

        /// <summary>The portal you came through, else your saved spot on this map, else the save point.</summary>
        private Vector3 SpawnPoint(CharacterRecord record, Vector3 save, string arrivalPortal)
        {
            if (World != null && !string.IsNullOrEmpty(arrivalPortal))
            {
                var portal = World.Layout.Portals.Find(p => string.Equals(p.Portal.Id, arrivalPortal, System.StringComparison.OrdinalIgnoreCase));
                if (portal != null)
                {
                    return WorldBuilder.ToWorld(portal.Arrival);
                }
            }

            if (record.HasSavedPosition && record.MapId == FieldContext.MapId)
            {
                var saved = new Vector3(record.PosX, record.PosY, record.PosZ) + FieldContext.Origin;
                if (World == null || World.Layout.IsWalkable(new GroundPoint(saved.x, saved.z)))
                {
                    return saved;
                }
            }

            return save;
        }

        private static void Greet(CharacterRecord record, GameSession session)
        {
            var map = FieldContext.Map;
            ChatLog.System(map != null
                ? $"Welcome to {map.Name}, {record.Name}! {map.Description}"
                : $"Welcome to {FieldContext.MapName}, {record.Name}! Midgard shivers under the Fimbulwinter.");
            ChatLog.System("Left-click to move/attack/talk · F1–F10 hotkeys · Alt+A status · Alt+S skills · Alt+E items · Alt+Q equipment · " +
                           "Ctrl+Tab map · Enter to chat · @help");
            if (map != null && map.IsTown)
            {
                ChatLog.System("Ásta sells supplies, Hrafn arms you, Brokk forges and repairs, the Norn Courier stores and teleports, Sigrun changes jobs, " +
                               "Gunnar rents Pushcarts. The south gate leads to the Whisperwood Plains.");
            }

            var online = OnlineSession.Current;
            if (online != null)
            {
                ChatLog.System($"Online on {online.RealmName}. Chat: plain text = map, %text = party, $text = guild, /sh text = shout, " +
                               "/w Name text = whisper. Click a player to trade, party or browse their stall. Alt+Z party · Alt+G guild.");
            }

            if (session.IsTemporaryCharacter)
            {
                ChatLog.Notice("Temporary character (scene played directly). Start from RH_Login to use saved characters.");
            }
        }

        private void Update()
        {
            if (_player != null && Time.time >= _nextAutosave)
            {
                _nextAutosave = Time.time + autosaveSeconds;
                _player.SaveNow();
            }
        }

        /// <summary>Esc menu → "Character Select".</summary>
        public void ReturnToCharacterSelect()
        {
            if (_player != null)
            {
                _player.WriteBackToRecord();
            }

            GameSession.Instance.ReturnToCharacterSelect();
        }

        private void OnApplicationQuit()
        {
            if (_player != null)
            {
                _player.SaveNow();
            }
        }

        private void OnDrawGizmosSelected()
        {
            Gizmos.color = new Color(1f, 0.85f, 0.3f, 0.4f);
            Gizmos.DrawWireCube(transform.position, mapSize);
        }
    }
}
